### ISSUE TITLE
Need example uart stm32 mti-1

### ISSUE THREAD

**Issue by maohuynh-embedded** [Scottapotamas/xsens-mti#13]
I need to read mti-1 data using uart of stm32. But it doesn't seem to work with the library.

**Comment by Scottapotamas** [comment]
You need to provide more information, and better descriptions of your troubleshooting steps.

This library is known to work with the single-digit series parts, and is used with MTi-2 and MTi-7 modules.

Please check the following:

1. Have you confirmed your STM32 is able to read serial data correctly, and is it configured for the correct baudrate that the IMU is using (typically 115200 by default?).
2. Are you correctly ensuring the ~RST pin on the module is high.
3. Have you configured the IMU before trying to use it, or is this the first time you're trying to use the IMU? You may need to configure your desired output packets and rates before getting the data you're expecting.
4. If possible, use an oscilloscope or logic analyser on the TX and RX pins of the module. The default configuration typically has the MTi sending packets automatically.
5. Please describe how you are configuring the xsens-mti library, and how/where you're handling the callbacks to see the inbound data.
6. Provide any additional descriptions of your firmware's build system/environment (i.e. STM32Cube, CMake, Arduino, PlatformIO, other).

**Comment by maohuynh-embedded** [comment]
Your library works fine with xsens_mti_parse_buffer. Thanks for your contribution. I close the ticket
